# Generated by Django 5.2.1 on 2025-06-09 07:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chatbotapi', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='chatbot',
            options={'verbose_name': 'Chatbot Configuration', 'verbose_name_plural': 'Chatbot Configurations'},
        ),
    ]
