# Generated by Django 5.2.1 on 2025-05-29 10:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chatbotapi', '0002_chatbot_delete_chatbotmap'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='chatbot',
            options={'ordering': ['name'], 'verbose_name': 'Chatbot Configuration', 'verbose_name_plural': 'Chatbot Configurations'},
        ),
        migrations.RemoveField(
            model_name='chatbot',
            name='config',
        ),
        migrations.RemoveField(
            model_name='chatbot',
            name='user',
        ),
        migrations.AddField(
            model_name='chatbot',
            name='configuration',
            field=models.JSONField(default={}, help_text='The JSON configuration of the chatbot flow.'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='chatbot',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='chatbot',
            name='name',
            field=models.CharField(help_text='The unique name of the chatbot.', max_length=255, unique=True),
        ),
    ]
